steps:
  # Build Docker Image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t", "gcr.io/project-prn231-gr3/api-vnpay-service:$COMMIT_SHA",
        "-f", "api-vnpay-service/Dockerfile",
        "."
      ]

  # Push Docker Image lên Google Container Registry (GCR)
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/project-prn231-gr3/api-vnpay-service:$COMMIT_SHA"]

  # Deploy lên Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run", "deploy", "api-ai-service",
        "--image", "gcr.io/project-prn231-gr3/api-vnpay-service:$COMMIT_SHA",
        "--region", "asia-east1",
        "--platform", "managed",
        "--allow-unauthenticated"
     
      ]

# Define a Google Cloud Storage bucket for build logs
logsBucket: "gs://api-service-log/"

images:
  - "gcr.io/project-prn231-gr3/api-vnpay-service"

# Set build timeout to 15 minutes
timeout: 600s
